# -*- coding: utf-8 -*-
"""Copy of Week1_assignment_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZKfs_g87jOq0_JLdQ9zV_rw6Kf4Gk3lW

<h3> Instructions </h3>
<br>
<p>1. Open the notebook file that needs to be copied and edited.<br>
2. Go to the "File" tab in the notebook's menu bar.<br>
3. Select "Save to Drive" to create a copy of the notebook in your own Google Drive.<br>
4. Once the notebook is saved to your Drive, open it for editing.<br>
<br>
To work on the exercises in the notebook, follow these steps:<br>
1. Read the instructions and explanations provided for each exercise carefully<br>
2. Write your code solutions for each exercise in the designated code cells.<br>
3. Download the dataset (.csv file) shared in the folder and upload it to the colab session.<br>

Important Note: It is recommended to read and understand the exercises thoroughly, as questions related to this assignment may be asked in a quiz.</p>

## Welcome To The Week1 Assignment
 
#### In this assignment we will analyze the Titanic dataset with the help of pandas <br>

![Titanic](https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/bil0510_rms-titanic_647_060515043509.jpg?size=1200:675)

`Note: You will be asked various question from this assignment in the Google Form, and also you need to submit this notebook. So Kindly maintain this Notebook Properly`

### 1) Start this assignment by importing all the important Libraries
for eg. import pandas as pd
"""

import pandas as pd
import csv

"""### 2) Read the csv file and assign it to a variable

Note: Download the titanic.csv file from the google drive, and place it in the folder same as this notebook
"""

csv_data = pd.read_csv('/content/titanic.csv')
 
print(csv_data)

"""#### Display the first 5 entries of DataFrame
Hint: use head() function
"""

first_5 = csv_data.head(5)
print(first_5)

"""#### Display the last 5 entries of DataFrame
Hint: use tail() function
"""

first_5 = csv_data.tail(5)
print(first_5)

"""### 3) Display the shape of the Dataframe"""

csv_data.shape

"""### 4) Print all the columns of the Dataframe"""

pd.set_option('display.max_columns', None)
csv_data.head()

"""About Data:<br>
__PassangerId__: Passanger Number<br>
__Survived__: Dead(0), Alive(1)<br>
__PClass__: Class in which the passenger is travelling<br>
__Name__: Name of the Passenger<br>
__Sex__: Male,Female<br>
__Age__: Age of the passenger<br>
__SibSp__: Number of siblings<br>
__Parch__: # of siblings / spouses aboard the Titanic<br>
__Ticket__: Ticket number<br>
__Fare__: Passenger Fare<br>
__Cabin__: Cabin number<br>
__Embarked__: Port of Embarkation (C = Cherbourg, Q = Queenstown, S = Southampton)<br>

### 5) Print the unique values in each column
"""

for col in csv_data:
    print(csv_data[col].unique())

"""### 6) Find the columns that has null values in them

Hint: You can use isnull() function
"""

csv_data.isnull().sum()

"""### 7) Show various statistics of all the numerical columns

Hint: Use describe()
"""

csv_data.describe(include='all')

"""### 8) Drop the column that has maximum null values and update the Dataframe"""

colum=csv_data.count().idxmin()
csv_data = csv_data.drop(colum, axis=1)

"""### 9) Display the data type of the remaining columns(use updated dataframe)"""

result = csv_data.dtypes
print(result)

"""### 10) Display the sex ratio (female /male)
use value_counts()
"""

csv_data['Sex'].value_counts(normalize=True)

"""### 11) Find the number of people that Survived"""

csv_data['Survived'].eq(1).sum()

"""### 12) Find the person with maximum and minimum age
use .max() and .min() <br>
You need to print the row of the dataframe where the person with max and min age is present
"""

print(csv_data[csv_data.Age == csv_data.Age.max()])

print(csv_data[csv_data.Age == csv_data.Age.min()])

"""### 13) Find the number of Class 2 tickets sold"""

csv_data['Pclass'].value_counts()

"""### 14) Find the number of females who survived the crash"""

table = pd.crosstab(csv_data['Survived'],csv_data['Sex'])
print (table)

"""### 15) Find the number of people who survived the crash and who paid fare less than 200"""

table = pd.crosstab(csv_data['Survived'],csv_data['Fare'])
print (table)

"""### Extra Questions (Will not be considered for evaluation)

Try plotting different columns with each other, and see what inferences you can think about the dataset
"""